# Generated by Django 4.2.7 on 2023-11-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('verify_code', models.CharField(blank=True, max_length=4, null=True, unique=True)),
                ('referral_code', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('invite_code', models.CharField(blank=True, max_length=15, null=True, unique=True)),
            ],
        ),
    ]
