# Generated by Django 4.2.7 on 2023-11-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='user',
            name='invite_code',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='инвайт код'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, verbose_name='номер'),
        ),
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='реферальный код'),
        ),
    ]
