# Generated by Django 4.2.7 on 2023-11-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь сервиса', 'verbose_name_plural': 'Пользователи сервиса'},
        ),
        migrations.AlterField(
            model_name='user',
            name='invite_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True, verbose_name='инвайт код'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, verbose_name='номер'),
        ),
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True, verbose_name='реферальный код'),
        ),
        migrations.AlterField(
            model_name='user',
            name='verify_code',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True, verbose_name='код для авторизации'),
        ),
    ]
