# Generated by Django 4.2.7 on 2023-11-19 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
