# Generated by Django 4.2.7 on 2023-11-23 18:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_phone_user_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.BigIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(limit_value=10000000000), django.core.validators.MaxValueValidator(limit_value=99999999999)], verbose_name='Номер телефона'),
        ),
    ]
