# Generated by Django 4.2.7 on 2023-11-20 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_email_remove_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='verify_code',
        ),
    ]
