# Generated by Django 4.2.7 on 2023-11-24 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_alter_invitecode_options_and_more'),
        ('users', '0005_remove_user_username_alter_user_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='imputed_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.imputedcode'),
        ),
        migrations.AddField(
            model_name='user',
            name='invite_code',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='service.invitecode'),
            preserve_default=False,
        ),
    ]
