# Generated by Django 4.2.7 on 2023-11-24 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_alter_imputedcode_invite_code'),
        ('users', '0006_user_imputed_code_user_invite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='imputed_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_users', to='service.imputedcode'),
        ),
        migrations.AlterField(
            model_name='user',
            name='invite_code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='service.invitecode'),
        ),
    ]
