# Generated by Django 4.2.7 on 2023-11-23 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0002_invitecode_code_invitecode_user_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitecode',
            options={'verbose_name': 'Инвайт код', 'verbose_name_plural': 'Инвайт коды'},
        ),
        migrations.AlterField(
            model_name='invitecode',
            name='code',
            field=models.IntegerField(default='720651', unique=True, verbose_name='Инвайт код'),
        ),
        migrations.AlterField(
            model_name='invitecode',
            name='users_invited',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
