# Generated by Django 4.2.7 on 2023-11-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_invitecode_options_alter_invitecode_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitecode',
            name='code',
            field=models.IntegerField(unique=True, verbose_name='Инвайт код'),
        ),
    ]
