# Generated by Django 4.2.7 on 2023-11-24 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_invitecode_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitecode',
            old_name='users_invited',
            new_name='invited_users',
        ),
    ]
