# Generated by Django 4.2.7 on 2023-11-24 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0005_rename_users_invited_invitecode_invited_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitecode',
            name='invited_users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imputed_code', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
