# Generated by Django 4.2.7 on 2023-11-24 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_alter_invitecode_invited_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitecode',
            options={'verbose_name': 'Инвайт код'},
        ),
        migrations.RemoveField(
            model_name='invitecode',
            name='invited_users',
        ),
        migrations.RemoveField(
            model_name='invitecode',
            name='user_owner',
        ),
        migrations.CreateModel(
            name='ImputedCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='imputed_code', to='service.invitecode')),
            ],
            options={
                'verbose_name': 'Введённый код',
            },
        ),
    ]
