# Generated by Django 4.2.7 on 2023-11-24 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_alter_invitecode_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imputedcode',
            name='invite_code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invited_users', to='service.invitecode'),
        ),
    ]
